services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - app-data:/app/mount
    env_file:
      - ./.env

  mysql:
    image: mariadb:10.11
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env

  batch:
    build:
      context: ./batch
      dockerfile: Dockerfile
    volumes:
      - app-data:/app/mount
    profiles:
      - donotstart

volumes:
  app-data:
  mysql-data:

